[project]
name = "pypocketminer"
version = "0"

[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"pypocketminer.models" = ["**/*"]
"pypocketminer.data" = ["**/*"]
